{% set version = "1.12" %}
package:
  name: easydict
  version: {{ version }}
source:
  sha256: 0555ccc3a73d8614901b368b72c28ad476ecce177dbdf424c83e08c17a49e076
  url: https://pypi.io/packages/source/e/easydict/easydict-{{ version }}.tar.gz
build:
  noarch: python
  number: '0'
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
test:
  imports:
    - easydict
about:
  description: |
    *EasyDict* allows to access dict values as attributes (works recursively). 
    A Javascript-like properties dot notation for python dicts.

    =====
    USAGE
    =====

    ::

        >>> from easydict import EasyDict as edict
        >>> d = edict({'foo':3, 'bar':{'x':1, 'y':2}})
        >>> d.foo
        3
        >>> d.bar.x
        1
        
        >>> d = edict(foo=3)
        >>> d.foo
        3

  home: https://github.com/makinacorpus/easydict
  license: LGPL
  license_file: LICENSE
  summary: Access dict values as attributes (works recursively).
extra:
  recipe-maintainers:
    - zhaofeng-shu33
